### ISSUE TITLE
Function typedefs should avoid abbreviations

### ISSUE THREAD

**Issue by ochafik** [dart-lang/func#1]
(as [per style guide](https://www.dartlang.org/effective-dart/design/#avoid-abbreviations))

Suggestion (same as [in Scala](http://www.scala-lang.org/api/rc2/scala/package.html)): `FunctionN` instead of `FuncN`.

**Comment by jacob314** [comment]
I ran the abbreviated names past the style arbiter (rnystrom) and he was ok with them for this case.
